name: Code Insights SD Policy scan
  
on:
  push:
  pull_request:
  
jobs:
  ci_policy_scan:
    runs-on: ubuntu-latest
    env:
     SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
     TARGET_BRANCH: ${{ github.event.pull_request.base.ref || 'master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
    - name: Execute script 
      shell: bash
      run: |
       git fetch origin
       
