name: Code Insights SD Policy scan
  
on:
  push:
  pull_request:
  
jobs:
  ci_policy_scan:
    runs-on: ubuntu-latest
    env:
     SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
     TARGET_BRANCH: ${{ github.event.pull_request.base.ref || 'master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
    - name: Send notification to JIRA
      uses: alstn2468/jira-publish-notification@v1.0.0
      with:
        GITHUB_TOKEN: '${{ secrets.G_TOKEN }}'
        JIRA_CLIENT_ID: '${{ secrets.JIRA_CLIENT_ID }}'
        JIRA_CLIENT_SECRET: '${{ secrets.JIRA_CLIENT_SECRET }}'
        JIRA_INSTANCE: 'sohardh'
        DEPLOY_ENVIRONMENT: 'dev'
    - name: Execute script 
      shell: bash
      run: |
       git fetch origin
       git checkout "${TARGET_BRANCH}"
       git checkout "${SOURCE_BRANCH}"
 
       CHANGED_FILES=$(git diff --diff-filter=ACMR --name-only --ignore-submodules $(git merge-base "${SOURCE_BRANCH}" "${TARGET_BRANCH}") "${SOURCE_BRANCH}")
       if [ "x${CHANGED_FILES}" == "x" ]; then
         echo "Skipped Code Insights SD Policy Scan as git diff returned empty file list" && exit 0
       fi
        
       wget --quiet -O code-insights-cli.jar https://download.blueoptima.com/codeinsights/code-insights-cli.jar
        
       SD_CMD="java -DCI_CORE_HOST=https://${integrator_host}:${port} -DCI_INSTALL_ID=github-actions-${project-name} -jar code-insights-cli.jar --fail-policy=high --channel=ci-cd --sd"
       while IFS= read -r file; do
         SD_CMD="$SD_CMD \"$file\""
       done <<< "${CHANGED_FILES}"
 
       eval "${SD_CMD}"

